<?php
/**
 * @file
 * General functions and hook implementations.
 *
 * @see https://github.com/reevoo/reevoomark-php-api
 *
 */

/**
 * Implements hook_libraries_info()
 */
function reevoomark_libraries_info() {
  return array(
    'reevoomark-php-api' => array(
      'title' => 'PHP API for embedded reevoomarks',
      'vendor url' => 'http://www.reevoo.com',
      'download url' => 'https://github.com/reevoo/reevoomark-php-api',
      'path' => 'lib',
      'version arguments' => array(
        'file' => 'lib/reevoo_mark.php',
        'pattern' => '~"ReevooMark PHP Widget/(.*?)"~',
        'lines' => 200,
      ),
      'files' => array(
        'php' => array(
          'reevoo_mark.php',
        ),
      ),
    ),
  );
}

/**
 * Implements of hook_menu().
 */
function reevoomark_menu() {
  $items['admin/config/system/reevoomark'] = array(
    'title' => 'ReevooMark',
    'description' => 'Change the setting configuration when using ReevooMark.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reevoomark_admin_settings'),
    'access arguments' => array('administer reevoomark settings'),
    'file' => 'reevoomark.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function reevoomark_theme() {
  return array(
    'reevoomark_body' => array(
      'variables' => array(
        'delta' => NULL,
        'body' => NULL,
      ),
    ),
    'reevoomark_overall_score' => array(
      'variables' => array('score' => NULL),
    ),
    'reevoomark_best_price' => array(
      'variables' => array(
        'currency_symbol' => NULL,
        'price' => NULL,
        'url' => NULL,
      ),
    ),
  );
}

/**
 * Implements of hook_block_info().
 */
function reevoomark_block_info() {
  $blocks['first_two_reviews'] = array(
    'info' => t('ReevooMark first two reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['embeddable_reviews'] = array(
    'info' => t('ReevooMark embeddable reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['embeddable_reviews_slim'] = array(
    'info' => t('ReevooMark slim embeddable reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['offers'] = array(
    'info' => t('ReevooMark offers'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['overall_score'] = array(
    'info' => t('ReevooMark overall score'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['best_price'] = array(
    'info' => t('ReevooMark best price'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements of hook_block_view().
 */
function reevoomark_block_view($delta = '') {
  $block = array();

  $sku = reevoomark_sku();
  if (empty($sku)) {
    // No sku = no review
    return $block;
  }

  switch ($delta) {
    case 'overall_score':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_first_two_reviews'), $sku)) {

        if ($score = $mark->getOverallScore()) {
          $block['content'] = array(
            '#score' => $score,
            '#theme' => 'reevoomark_overall_score',
          );
        }

      }
      break;
    case 'best_price':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_offers'), $sku)) {

        if ($price = $mark->getBestPrice()) {
          $block['content'] = array(
            '#currency_symbol' => variable_get('reevoomark_currency_symbol', '£'),
            '#price' => $price,
            '#url' => $mark->getBestPriceLink(),
            '#theme' => 'reevoomark_best_price',
          );
        }

      }
      break;
    case 'first_two_reviews':
    case 'embeddable_reviews':
    case 'embeddable_reviews_slim':
    case 'offers':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_' . $delta), $sku)) {
        $body = $mark->body();
        if (!empty($body)) {
          $block['content'] = array(
            '#body' => $body,
            '#delta' => $delta,
            '#theme' => 'reevoomark_body',
          );
        }
      }
      break;
  }

  return $block;
}

/**
 * Get the sku of the product whose reviews are wanted.
 *
 * Defaults to nid of current page.
 *
 * @see hook_reevoomark_sku_alter($sku)
 */
function reevoomark_sku() {
  $sku = '';

  $menu_object = menu_get_object();
  if (!empty($menu_object->nid)) {
    $sku = $menu_object->nid;
  }
  drupal_alter('reevoomark_sku', $sku);

  return $sku;
}

/**
 * Get the ReevooMarkService object.
 *
 * @return ReevooMarkService
 */
function reevoomark_get_service($url, $sku) {
  $cache = '/tmp'; //@todo make cache configurable and not necessarily a path. memcache, db etc.

  if (($library = libraries_load('reevoomark-php-api')) && !empty($library['loaded'])) {
    $mark = new ReevooMarkService(
      '/tmp',
      trim($url),
      trim(variable_get('reevoomark_retailer')),
      $sku
    );

    return $mark;
  }

  return FALSE;
}

function theme_reevoomark_body($variables) {
  return '<div class="reevoomark_' . $variables['delta'] . '">' . $variables['body'] . '</div>';
}

function theme_reevoomark_best_price($variables) {
  $link = l($variables['currency_symbol'] . $variables['price'], $variables['url']);
  return '<div class="reevoomark_best_price">Buy it now for: ' . $link . '</div>';
}

function theme_reevoomark_overall_score($variables) {
  return '<div class="reevoomark_overall_score">
    <span class="label">Overall Score</span> <span class="score">' . $variables['score']
    . '</span></div>';
}
