<?php
/**
 * @file
 * General functions and hook implementations.
 *
 * @see https://github.com/reevoo/reevoomark-php-api
 *
 */

/**
 * Implements hook_libraries_info()
 */
function reevoomark_libraries_info() {
  return array(
    'reevoomark-php-api' => array(
      'title' => 'PHP API for embedded reevoomarks',
      'vendor url' => 'http://www.reevoo.com',
      'download url' => 'https://github.com/reevoo/reevoomark-php-api',
      'path' => 'lib',
      'version arguments' => array(
        'file' => 'lib/reevoo_mark.php',
        'pattern' => '~"ReevooMark PHP Widget/(.*?)"~',
        'lines' => 200,
      ),
      'files' => array(
        'php' => array(
          'reevoo_mark.php',
        ),
      ),
    ),
  );
}

/**
 * Implements of hook_menu().
 */
function reevoomark_menu() {
  $items['admin/config/system/reevoomark'] = array(
    'title' => 'ReevooMark',
    'description' => 'Change the setting configuration when using ReevooMark.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reevoomark_admin_settings'),
    'access arguments' => array('administer reevoomark settings'),
    'file' => 'reevoomark.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function reevoomark_theme() {
  return array(
    'reevoomark_body' => array(
      'variables' => array(
        'class' => NULL,
        'body' => NULL,
      ),
    ),
    'reevoomark_overall_score' => array(
      'variables' => array('score' => NULL),
    ),
    'reevoomark_best_price' => array(
      'variables' => array(
        'currency_symbol' => NULL,
        'price' => NULL,
        'url' => NULL,
      ),
    ),
  );
}

/**
 * Implements of hook_block_info().
 */
function reevoomark_block_info() {
  $blocks['first_two_reviews'] = array(
    'info' => t('ReevooMark first two reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['embeddable_reviews'] = array(
    'info' => t('ReevooMark embeddable reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['embeddable_reviews_slim'] = array(
    'info' => t('ReevooMark slim embeddable reviews'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['offers'] = array(
    'info' => t('ReevooMark offers'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['overall_score'] = array(
    'info' => t('ReevooMark overall score'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['best_price'] = array(
    'info' => t('ReevooMark best price'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements of hook_block_view().
 */
function reevoomark_block_view($delta = '') {
  $block = array();

  $sku = reevoomark_sku();
  if (empty($sku)) {
    // No sku = no review
    return $block;
  }

  switch ($delta) {
    case 'overall_score':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_first_two_reviews'), $sku)) {

        if ($score = $mark->getOverallScore()) {
          $block['content'] = array(
            '#score' => $score,
            '#theme' => 'reevoomark_overall_score',
            '#attached' => reevoomark_renderable_attached(),
          );
        }

      }
      break;
    case 'best_price':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_offers'), $sku)) {

        if ($price = $mark->getBestPrice()) {
          $block['content'] = array(
            '#currency_symbol' => variable_get('reevoomark_currency_symbol', '£'),
            '#price' => $price,
            '#url' => $mark->getBestPriceLink(),
            '#theme' => 'reevoomark_best_price',
            '#attached' => reevoomark_renderable_attached(),
          );
        }

      }
      break;
    case 'first_two_reviews':
    case 'embeddable_reviews':
    case 'embeddable_reviews_slim':
    case 'offers':
      if ($mark = reevoomark_get_service(variable_get('reevoomark_url_' . $delta), $sku)) {
        $body = $mark->body();
        if (!empty($body)) {
          $block['content'] = array(
            '#body' => $body,
            '#class' => $delta,
            '#theme' => 'reevoomark_body',
            '#attached' => reevoomark_renderable_attached(),
          );
        }
      }
      break;
  }

  return $block;
}

/**
 * The '#attached' part of the renderable array for including the required common js & css.
 */
function reevoomark_renderable_attached() {
  return array(
    'css' => array(
      'http://mark.reevoo.com/stylesheets/reevoomark/embedded_reviews.css',
    ),
    'js' => array(
      'http://mark.reevoo.com/reevoomark/' . variable_get('reevoomark_retailer') . '.js',
    ),
  );
}

/**
 * Get the sku of the product whose reviews are wanted.
 *
 * Defaults to nid of current page.
 *
 * @see hook_reevoomark_sku_alter($sku)
 */
function reevoomark_sku() {
  $sku = '';

  $menu_object = menu_get_object();
  if (!empty($menu_object->nid)) {
    $sku = $menu_object->nid;
  }
  drupal_alter('reevoomark_sku', $sku);

  return $sku;
}

/**
 * Allow other modules to provide overriding classes.
 *
 */
function reevoomark_load_classes() {
  static $info;

  if (!is_array($info)) {
    // The service class
    // The class must implement ReevooMarkServiceInterface
    // Based on extending the ReevooMark class from the library
    $info['service_class'] = variable_get(
      'reevoomark_service_class',
      array(
        'file' => 'ReevooMarkService',
        'module' => 'reevoomark',
        'class' => 'ReevooMarkService',
      )
    );

    // The document class
    // Based on extending the ReevooMarkDocument class from the library
    $info['document_class'] = variable_get(
      'reevoomark_document_class',
      array(
        'file' => 'ReevooMarkServiceDocument',
        'module' => 'reevoomark',
        'class' => 'ReevooMarkServiceDocument',
      )
    );

  }

  // Load the libray classes
  if (($library = libraries_load('reevoomark-php-api')) && !empty($library['loaded'])) {

    // Load the extending class files if not already loaded
    foreach ($info as $class_info) {
      if (!class_exists($class_info['class']) && isset($class_info['file']) && isset($class_info['module'])) {
        module_load_include('php', $class_info['module'], $class_info['file']);
      }
    }

    return $info;
  }

  return FALSE;
}

/**
 * Get the ReevooMarkService object.
 *
 * @return ReevooMarkServiceInterface
 */
function reevoomark_get_service($url, $sku) {

  $url = trim($url);
  $sku = trim($sku);
  $retailer = trim(variable_get('reevoomark_retailer'));

  if ($info = reevoomark_load_classes()) {
    $class = $info['service_class']['class'];

    if (isset($info['document_class']['class'])) {
      // Use the module's document class
      return new $class($url, $retailer, $sku, $info['document_class']['class']);
    }
    else {
      return new $class($url, $retailer, $sku);
    }

  }

  return FALSE;
}

/**
 * Returns HTML from Reevoo wrapped in a div.
 *
 * @param $variables
 *   An associative array containing:
 *   - class: A class name that will be prefixed by 'reevoomark_'.
 *   - body: The html returned by Reevoo.
 *
 * @ingroup themeable
 */
function theme_reevoomark_body($variables) {
  return '<div class="reevoomark_' . $variables['class'] . '">' . $variables['body'] . '</div>';
}

/**
 * Returns the best price wrapped in a div.
 *
 * @param $variables
 *   An associative array containing:
 *   - price: The best price.
 *   - url: The url of where to by the product at that price.
 *
 * @ingroup themeable
 */
function theme_reevoomark_best_price($variables) {
  $link = l($variables['currency_symbol'] . $variables['price'], $variables['url']);
  return '<div class="reevoomark_best_price">Buy it now for: ' . $link . '</div>';
}

/**
 * Returns the overall score wrapped in a div.
 *
 * @param $variables
 *   An associative array containing:
 *   - score: The score.
 *
 * @ingroup themeable
 */
function theme_reevoomark_overall_score($variables) {
  return '<div class="reevoomark_overall_score">
    <span class="label">Overall Score</span> <span class="score">' . $variables['score']
    . '</span></div>';
}
